### ISSUE TITLE
tailwind responsivity not working as expected

### ISSUE THREAD

**Issue by majorminors** [joshhanley/slides#10]
tailwind breakpoints not functioning as expected with text sizes
appears to be over-ridden by largest size class present in element

**Comment by majorminors** [comment]
appears to affect breakpoints across the board

**Comment by majorminors** [comment]
not quite. width sizing is responsive. text no. border properties no. grid properties no.

**Comment by majorminors** [comment]
justifying content also works responsively

**Comment by joshhanley** [comment]
Can you give me some screenshots of this as I can't work out what you mean

**Comment by majorminors** [comment]
Will see if this is a consequence of my layout, or if I can fix it regardless with a different layout.

**Comment by majorminors** [comment]
fixed in b317006
