### ISSUE TITLE
slide preview doesn't display slides

### ISSUE THREAD

**Issue by majorminors** [joshhanley/slides#12]

**Comment by majorminors** [comment]
can't figure out how I broke this, sorry

**Comment by joshhanley** [comment]
Fixed temporarily in 6a9f4dcad852e09ae1ad93ea640445bfb32d63e5 by ensuring presentation mode isn't on initially.

Previews are not being generated if the preview panel isn't visible on screen. So still a bug that needs to be fixed.

**Comment by joshhanley** [comment]
Issue is no longer happening since previews have been changed to Vue e736f7c02905bd17319db8c2788cd19b78ca4988
