### ISSUE TITLE
not compatible with edge

### ISSUE THREAD

**Issue by majorminors** [joshhanley/slides#14]
doesn't appear to work on edge - background appears, but slides do not. preview mode half open, despite being toggled 'false' in code

**Comment by joshhanley** [comment]
Seems to be working fine in Edge?

![image](https://user-images.githubusercontent.com/882837/80294786-7fb7cd00-87af-11ea-8f4a-f3d349b1428c.png)

**Comment by majorminors** [comment]
Might have been related to the fact I had to remote desktop to test on edge.

**Comment by joshhanley** [comment]
I have tested it again now we have move to Vue and it all seems to be running happily. Closing for now. Reopen if it still has issues.
